/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ApiError {
    err: string;
    message: string;
    cause: string;
}

export interface AppUser {
    uid: string;
    familyName: string;
    givenName: string;
}

export interface HouseholdMetadata {
    guid: string;
    name: string;
}

export interface ExpenseWindowMetadata {
    guid: string;
    startDate: string;
    paidDate?: string;
}

export interface ExpenseCategoryMetadata {
    guid: string;
    name: string;
    description: string;
    color: string;
}

export interface ExpenseCategoryPercentage {
    percentage: number;
    user: AppUser;
}

export type ExpenseCategory = ExpenseCategoryMetadata & { percentages: Array<ExpenseCategoryPercentage> };

export interface DollarAmount {
    dollars: number;
    cents: number;
}

export interface VariableExpenseMetadata {
    guid: string;
    paidOn: string;
    description: string;
    amount: DollarAmount;
}

export interface FixedExpenseMetadata {
    guid: string;
    description: string;
    amount: DollarAmount;
}

export type VariableExpense = VariableExpenseMetadata & { paidBy: AppUser; category?: ExpenseCategoryMetadata };
export type FixedExpense = FixedExpenseMetadata & { defaultPaidBy: AppUser; category: ExpenseCategoryMetadata };
export type FixedExpenseInstance = FixedExpenseMetadata & { paidBy: AppUser; category: ExpenseCategoryMetadata };
export type ExpenseWindow = ExpenseWindowMetadata & { variableExpenses: Array<VariableExpense>; fixedExpenses: Array<FixedExpenseInstance> };
export type Household = HouseholdMetadata & { currentWindow: ExpenseWindow; recentWindows: Array<ExpenseWindowMetadata> };

export interface WindowSummaryCategoryTotal {
    category: ExpenseCategoryMetadata;
    total: DollarAmount;
}

export interface WindowSummaryUserSpending {
    user: AppUser;
    total: DollarAmount;
}

export interface WindowSummaryUserCategoryTotals {
    user: AppUser;
    categories: Array<WindowSummaryCategoryTotal>;
}

export interface WindowSummary {
    total: DollarAmount;
    byUser: Array<WindowSummaryUserSpending>;
    byCategory: Array<WindowSummaryCategoryTotal>;
    userCategory: Array<WindowSummaryUserCategoryTotals>;
}

export type GetHouseholdsForCurrentUserResponse = Array<HouseholdMetadata>;

export interface HouseholdCreateRequest {
    name: string;
}

export interface VariableExpenseCreateRequest {
    description: string;
    paidByUserID: string;
    amount: DollarAmount;
    paidOn: string;
    categoryGuid: string;
}

export interface FixedExpenseCreateRequest {
    description: string;
    amount: DollarAmount;
    categoryGuid: string;
    defaultPaidByUID: string;
}

export interface ExpenseCategoryCreateRequest {
    name: string;
    description: string;
    color: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
