/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ApiError {
    err: string;
    message: string;
    cause: string;
}

export interface AppUser {
    familyName: string;
    givenName: string;
}

export interface HouseholdMetadata {
    guid: string;
    name: string;
}

export interface ExpenseWindowMetadata {
    guid: string;
    startDate: string;
    paidDate?: string;
}

export interface ExpenseCategory {
    guid: string;
    name: string;
    description: string;
    color: string;
}

export interface DollarAmount {
    dollars: number;
    cents: number;
}

export interface VariableExpenseMetadata {
    guid: string;
    paidOn: string;
    description: string;
    amount: DollarAmount;
}

export interface FixedExpenseMetadata {
    guid: string;
    description: string;
    amount: DollarAmount;
}

export type VariableExpense = VariableExpenseMetadata & { paidBy: AppUser; category?: ExpenseCategory };
export type FixedExpense = FixedExpenseMetadata & { paidBy: AppUser; category: ExpenseCategory };
export type ExpenseWindow = ExpenseWindowMetadata & { variableExpenses: Array<VariableExpense>; fixedExpenses: Array<FixedExpense> };
export type Household = HouseholdMetadata & { currentWindow: ExpenseWindow };
export type GetHouseholdsForCurrentUserResponse = Array<HouseholdMetadata>;

export interface HouseholdCreateRequest {
    name: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
