/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for HouseholdResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { GetHouseholdsForCurrentUserResponse, Household } from "../models";

@Injectable({ providedIn: "root" })
export class HouseholdResource {
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getHouseholdsForUser(resourceOptions: HttpResourceOptions<GetHouseholdsForCurrentUserResponse, unknown> & { defaultValue: NoInfer<GetHouseholdsForCurrentUserResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<GetHouseholdsForCurrentUserResponse>;
    getHouseholdsForUser(resourceOptions?: HttpResourceOptions<GetHouseholdsForCurrentUserResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<GetHouseholdsForCurrentUserResponse | undefined>;
    getHouseholdsForUser(resourceOptions?: HttpResourceOptions<GetHouseholdsForCurrentUserResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<GetHouseholdsForCurrentUserResponse | undefined> {

        let headers: HttpHeaders;
        if (requestOptions?.headers instanceof HttpHeaders) {
            headers = requestOptions.headers;
        } else {
            headers = new HttpHeaders(requestOptions?.headers as Record<string, string>);
        }
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/v1/household`,
                method: "GET",
                headers,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getHouseholdByGUID(householdGuid: Signal<string> | string, resourceOptions: HttpResourceOptions<Household, unknown> & { defaultValue: NoInfer<Household> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Household>;
    getHouseholdByGUID(householdGuid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Household, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Household | undefined>;
    getHouseholdByGUID(householdGuid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Household, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Household | undefined> {

        let headers: HttpHeaders;
        if (requestOptions?.headers instanceof HttpHeaders) {
            headers = requestOptions.headers;
        } else {
            headers = new HttpHeaders(requestOptions?.headers as Record<string, string>);
        }
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/v1/household/${typeof householdGuid === 'function' ? householdGuid() : householdGuid}`,
                method: "GET",
                headers,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
