/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { ExpenseCategoryResource } from "./expenseCategory.resource";
export { FixedExpenseResource } from "./fixedExpense.resource";
export { HouseholdResource } from "./household.resource";
export { WindowResource } from "./window.resource";
export { WindowSummaryResource } from "./windowSummary.resource";
