/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for WindowSummaryResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { WindowSummary } from "../models";

@Injectable({ providedIn: "root" })
export class WindowSummaryResource {
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getWindowSummaryByGuid(windowGuid: Signal<string> | string, resourceOptions: HttpResourceOptions<WindowSummary, unknown> & { defaultValue: NoInfer<WindowSummary> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<WindowSummary>;
    getWindowSummaryByGuid(windowGuid: Signal<string> | string, resourceOptions?: HttpResourceOptions<WindowSummary, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<WindowSummary | undefined>;
    getWindowSummaryByGuid(windowGuid: Signal<string> | string, resourceOptions?: HttpResourceOptions<WindowSummary, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<WindowSummary | undefined> {

        let headers: HttpHeaders;
        if (requestOptions?.headers instanceof HttpHeaders) {
            headers = requestOptions.headers;
        } else {
            headers = new HttpHeaders(requestOptions?.headers as Record<string, string>);
        }
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/v1/window/${typeof windowGuid === 'function' ? windowGuid() : windowGuid}/summary`,
                method: "GET",
                headers,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
