/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Household controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GetHouseholdsForCurrentUserResponse, HouseholdCreateRequest, HouseholdMetadata, Household, AppUser } from "../models";

@Injectable({ providedIn: "root" })
export class HouseholdService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getHouseholdsForUser(observe?: 'body', options?: RequestOptions<'json'>): Observable<GetHouseholdsForCurrentUserResponse>;
    getHouseholdsForUser(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetHouseholdsForCurrentUserResponse>>;
    getHouseholdsForUser(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetHouseholdsForCurrentUserResponse>>;
    getHouseholdsForUser(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/household`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createHousehold(householdCreateRequest?: HouseholdCreateRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<HouseholdMetadata>;
    createHousehold(householdCreateRequest?: HouseholdCreateRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<HouseholdMetadata>>;
    createHousehold(householdCreateRequest?: HouseholdCreateRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<HouseholdMetadata>>;
    /** Create a household object */
    createHousehold(householdCreateRequest?: HouseholdCreateRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/household`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, householdCreateRequest, requestOptions);
    }

    getHouseholdByGUID(householdGuid: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Household>;
    getHouseholdByGUID(householdGuid: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Household>>;
    getHouseholdByGUID(householdGuid: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Household>>;
    getHouseholdByGUID(householdGuid: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/household/${householdGuid}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getHouseholdMembers(householdGuid: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AppUser>>;
    getHouseholdMembers(householdGuid: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AppUser>>>;
    getHouseholdMembers(householdGuid: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AppUser>>>;
    getHouseholdMembers(householdGuid: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/household/${householdGuid}/members`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
